name: 3 Gun Ninja
favicon: null
layout_spectrum: 0.99436
typography_spectrum: 0.13148300861939788
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
